### ISSUE TITLE
CI fails with empty matrix vector

### ISSUE THREAD

**Issue by maxheld83** [DeterminateSystems/ci#19]
as of 1e15f9d85c7d782d1bba85cd6ccae10ff4e3a6a4, this (boilerplate) ci:

```yaml
name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "read"
    with:
      visibility: public
```

fails with:

```
Error when evaluating 'strategy' for job 'build'. DeterminateSystems/ci/.github/workflows/workflow.yml@main (Line: 97, Col: 18): Matrix vector 'systems' does not contain any values
```

For example: https://github.com/dataheld/nullkomma/actions/runs/13440007385
