### ISSUE TITLE
SSH PRIVATE KEYS

### ISSUE THREAD

**Issue by multivac61** [DeterminateSystems/ci#8]
Have you tested the SSH-PRIVATE-KEYS functionality from the [README](https://github.com/DeterminateSystems/ci/tree/main?tab=readme-ov-file#ssh-private-keys)?

I followed the steps outlined in https://github.com/marketplace/actions/webfactory-ssh-agent#usage

but still get errors like

```
git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
```

when running the action.

Here is my config (copy/paste from README): https://github.com/multivac61/nixos-config/blob/main/.github/workflows/determinate-ci.yml

**Comment by multivac61** [comment]
Ah, I think the inventory task should also have access to the ssh-agent action. Otherwise you cannot have a private `secrets` repo with agenix public keys.

Would you consider adding

```
      - uses: webfactory/ssh-agent@v0.9.0
        if: ${{ inputs.enable-ssh-agent }}
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}
```

to the `inventory` task too?
